version: "3.9"
services:
  web:
    build: services/frontend
    hostname: frontend
    container_name: frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  reader:
    build: services/reader
    hostname: reader
    container_name: reader
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend
  writer:
    build: services/writer
    hostname: writer
    container_name: writer
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
  frontend:
