version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  reader:
    build: services/reader
    ports:
      - "8081:8081"
    networks:
      - frontend
      - database
  writer:
    build: services/writer
    ports:
      - "8080:8080"
    networks:
      - backend
      - database
  redis:
    image: "redis:alpine"
    networks:
      - database

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  database:
    driver: bridge
