version: "3.9"
services:
  web:
    build: services/frontend
    container_name: web
    hostname: web
    depends_on:
      - reader
      - writer
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  reader:
    build: services/reader
    container_name: reader
    hostname: reader
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - backend
      - db
  writer:
    build: services/writer
    container_name: writer
    hostname: writer
    depends_on:
      - redis
    ports:
      - "8081:8081"
    networks:
      - backend
      - db
  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - db

networks:
  frontend:
  backend:
  db:
